### ISSUE TITLE
pack more punch

### ISSUE THREAD

**Issue by dominictarr** [protozoa-nz/protozoa-nz.github.io#2]
I think we can make the copy more powerful. framing question: what does a potential client what to know, what gets them to click "contact"? I'm gonna go with: 1, have the skills, 2, not gonna mess me around 3 (I'm sure there is a 3rd thing)

I guess 1 is code and 2 is human. I think in "process" we want to at least give out one fact that we can build on later - like "we plan work in one week chunks, every week you'll get to see our progress".

A phrase like "If you're new to this space we would love to develop a process which works best for you and your project." assumes they know what they want... am wondering if we need to indicate we are flexible?
actually "we _like_ to plan..." suggests that.

I'm not suggesting that we use all the following information - but we can expand and then reduce it down.

## code

* I've written a number of very popular modules, such as https://www.npmjs.com/package/JSONStream https://www.npmjs.com/package/rc or https://www.npmjs.com/package/pull-stream
* @mixmix @pietgeursen how many people have you taught to code?
* how many cumulative years experience do we have? (I've been doing node.js since... oh damn... 2010)
* and of course, secure-scuttlebutt. would explaining this be more distracting? unless they arrive because they heard about this?

## human

* lots of teaching experience obviously
* given conference talks
* [pithy one liners](https://twitter.com/dominictarr/status/629992939738005504)
* how to give the impression that we are good listeners, not just good speakers?
* tech for non-tech

## process

What do we need to get across in this section? I figure, unless the client has hired software contractors before (I'm guessing, more often not) then I feel this section is more for our benefit - to set a realistic expectations.

**Comment by mixmix** [comment]
Nice points  dominic. Check out some work piet and i did on a branch
called... Rework (or similar, there is only one  branch)

**Comment by dominictarr** [comment]
Okay this is better - I have a question - what is the person you are imaging reading our website?
is it a small business owner? is it someone non-technical with a startup idea?

And then I see the non-technical training is clearly a different kind of reader - like more a medium sized organization, probably being viewed by someone nearer the middle of the org?

I kinda irk when someone says they create "beautiful apps" because i feel that is something for others to judge, but not gonna bikeshed this cliche.

**Comment by mixmix** [comment]
re startup-idea - not them. Alanna and Silvia both cringed at the line "do you have an idea" because they anticipate it will attract random people with half-baked ideas and no money.

Yeah I think one of the reasons this is hard to write is to an extent what we think of particular language isn't the factor to debate on, it's what others read. I think there's still an authenticity and integrity thing ... but yeah.

I imagine the person reading this site is a 2-hop FoaF, e.g. Silvia has passed the link to someone she knows. So we have some credibility, but this person is trying to see what we're about. Ideally it's an organisation with enough money to be able to afford $100K + projects.

**Comment by dominictarr** [comment]
ha! they are probably right... lets change that line. did they suggest an alternative?

**Comment by mixmix** [comment]
Nope. Feel free to  change it directly.

The site is  not perfect but i think it's  done enough to  try  using. Or
maybe I'm just feeling tired  of trying to improve it.

What do you reckon

**Comment by dominictarr** [comment]
yeah, it's good enough.

**Comment by pietgeursen** [comment]
yep, good enough
